name: Flask Crud App

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Check Python Version and Install Dependencies
      run: |
        py --version
        py -m pip install --upgrade pip
        py -m pip install -r requirements.txt
    - name: Run the Flask Application
      run: |
        flask db init
        flask db migrate -m "entries table"
        flask db upgrade
        flask run
    # - name: Test with pytest
    #   run: |
    #     pytest
