name: Flask Crud App

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Flask App
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        # Run Unit Test for Flask App
        pytest
        # Check Lint Code
        flake8
        
    - name: Push Flask App image to DockerHub
      run: |
        docker build -t flask-app .
        docker tag flask-app:latest dukedocker687/flask-app:latest
        docker push dukedocker687/flask-app:latest
